stages:
  - build
  - archive

build-job:
  stage: build
  script:
    - mkdir -p bin
    - BUILDNO=$(git rev-list --count $CI_COMMIT_SHA)
    - find . -type f -print0 | xargs -0 sed -i "s/##jenkins-buildno##/$BUILDNO/g"
    - find . -type f -print0 | xargs -0 sed -i "s/##jenkins-builddate##/$(date --iso-8601=minutes)/g"
    - /srv/godot/Godot_v3.3.2-stable_linux_headless.64 --path DRR --export "Linux/X11" bin/drr-$CI_COMMIT_BRANCH-${BUILDNO}-linux.bin
    - /srv/godot/Godot_v3.3.2-stable_linux_headless.64 --path DRR --export "Windows Desktop" bin/drr-$CI_COMMIT_BRANCH-${BUILDNO}-win64.exe

archive-job:
  stage: archive
  script:
    - echo "archive stuff"
