variables:
  GIT_DEPTH: 99999

stages:
  - build
  - archive
  - upload

build-job:
  stage: build
  script:
    - mkdir -p bin
    - BUILDNO=$(git rev-list --count $CI_COMMIT_SHA)
    - find . -type f -print0 | xargs -0 sed -i "s/##ci-buildno##/$BUILDNO/g"
    - find . -type f -print0 | xargs -0 sed -i "s/##ci-builddate##/$(date --iso-8601=minutes)/g"
    - /srv/godot/Godot_v3.3.2-stable_linux_headless.64 --path DRR --export "Linux/X11" bin/drr-$CI_COMMIT_BRANCH-${BUILDNO}-linux.bin
    - /srv/godot/Godot_v3.3.2-stable_linux_headless.64 --path DRR --export "Windows Desktop" bin/drr-$CI_COMMIT_BRANCH-${BUILDNO}-win64.exe
  artifacts:
    paths:
    - bin

archive-job:
  stage: archive
  dependencies: 
    - build-job
  script:
    - BUILDNO=$(git rev-list --count $CI_COMMIT_SHA)
    - cd bin
    - zip drr-$CI_COMMIT_BRANCH-${BUILDNO}-win64.zip drr-$CI_COMMIT_BRANCH-${BUILDNO}-win64.exe drr-$CI_COMMIT_BRANCH-${BUILDNO}-win64.pck
    - zip drr-$CI_COMMIT_BRANCH-${BUILDNO}-linux.zip drr-$CI_COMMIT_BRANCH-${BUILDNO}-linux.bin
    - rm drr-$CI_COMMIT_BRANCH-${BUILDNO}-win64.exe drr-$CI_COMMIT_BRANCH-${BUILDNO}-win64.pck
    - rm drr-$CI_COMMIT_BRANCH-${BUILDNO}-linux.bin
  artifacts:
    paths:
      - "bin/*.zip"

upload-job:
  stage: upload
  dependencies:
    - archive-job
  only:
    refs:
      - master
  script:
    - ls -hla